import { describe, expect, it } from 'vitest';
import { createManualShelterDraft, validateShelterDraft, shelterRisk } from './shelter.ts';
import { listShelterProfiles, saveShelterProfile, deleteShelterProfile } from './shelter-storage.ts';
import type { ShelterInput } from './workspace-types.ts';
import fixtures from '../../fixtures/shelter-profiles.json';
export const shelterInput: ShelterInput={animal:{id:'a',name:'초코',species:'dog',ageMonths:null},memos:[{id:'m1',date:'2026-09-20',role:'staff',text:'사람을 좋아함. 다른 개를 보면 짖음. 발 만지면 피함.'},{id:'m2',date:'2026-09-21',role:'volunteer',text:'다른 개와 잘 놀았음.'}]};
describe('shelter evidence',()=>{
  it('does not turn negated preferences into a positive introduction',()=>{const d=createManualShelterDraft({...shelterInput,memos:[{id:'m',date:'2026-09-20',role:'staff',text:'사람을 좋아하지 않아요.'}]});expect(d.sociability.people).not.toBe('observed_positive');expect(d.likes).toHaveLength(0);expect(d.adopterIntro.text).not.toContain('좋아');});
  it('preserves risk keywords across the source chunk boundary',()=>{expect(shelterRisk('가'.repeat(7999)+'구토')).toContain('구토');});
  for(const fixture of fixtures) it(`fixture: ${fixture.id}`,()=>{const d=createManualShelterDraft(fixture.input as ShelterInput);expect(validateShelterDraft(d)).toEqual([]);for(const key of ['people','dogs','cats'] as const)if(fixture.expect[key])expect(d.sociability[key]).toBe(fixture.expect[key]);expect(d.cautions).toHaveLength(fixture.expect.cautions);for(const c of d.cautions)expect(d.adopterIntro.cautionLine).toContain(c.text);if(fixture.expect.safetyFlag)expect(d.safetyFlags).toContain(fixture.expect.safetyFlag);if(fixture.expect.introExclude)expect(d.adopterIntro.text).not.toContain(fixture.expect.introExclude);});
  it('rejects fabricated numbers, diagnosis and unknown quote mapping',()=>{for(const value of ['산책 99분','확진입니다','완벽한 천사']){const d=createManualShelterDraft(shelterInput);d.observations[0].text=value;d.observations[0].edited=true;expect(validateShelterDraft(d).length).toBeGreaterThan(0);}const d=createManualShelterDraft(shelterInput);d.observations[0].memoDate='2026-01-01';expect(validateShelterDraft(d).length).toBeGreaterThan(0);});
  it('rejects unsupported safety prose and malformed generation metadata',()=>{const d=createManualShelterDraft(shelterInput);d.safetyFlags=['100% 완치'];expect(validateShelterDraft(d).length).toBeGreaterThan(0);const e=createManualShelterDraft(shelterInput);e.generation={requestId:123,model:123,promptVersion:123,latencyMs:0,fallbackUsed:true} as never;expect(validateShelterDraft(e).length).toBeGreaterThan(0);});
  it('capacity never evicts existing records',()=>{localStorage.clear();const d=createManualShelterDraft(shelterInput);for(let n=0;n<50;n++)saveShelterProfile(d,'직원',true);const raw=localStorage.getItem('hanggo:shelter-profiles');expect(()=>saveShelterProfile(d,'직원',true)).toThrow(/50/);expect(localStorage.getItem('hanggo:shelter-profiles')).toBe(raw);localStorage.clear();});
  it('preserves all caution evidence and derives mixed sociality',()=>{const d=createManualShelterDraft(shelterInput);expect(d.sociability).toEqual({people:'observed_positive',dogs:'mixed',cats:'unknown'});expect(d.cautions).toHaveLength(2);for(const c of d.cautions) expect(d.adopterIntro.cautionLine).toContain(c.text);expect(validateShelterDraft(d)).toEqual([]);});
  it('rejects silent deletion of caution in observations or introduction',()=>{const d=createManualShelterDraft(shelterInput);d.adopterIntro.cautionLine='';expect(validateShelterDraft(d).length).toBeGreaterThan(0);const e=createManualShelterDraft(shelterInput);e.observations=e.observations.filter(o=>o.valence!=='caution');e.cautions=[];e.adopterIntro.cautionLine='';expect(validateShelterDraft(e).length).toBeGreaterThan(0);});
  it('does not infer sociability from breed',()=>{const d=createManualShelterDraft({...shelterInput,memos:[{id:'m',date:'2026-09-20',role:'staff',text:'진돗개라 그런지 충성심이 강할 듯.'}]});expect(d.sociability.people).toBe('unknown');expect(d.adopterIntro.text).not.toContain('충성심');});
  it('requires approval and refuses corruption without replacing stored bytes',()=>{localStorage.clear();const d=createManualShelterDraft(shelterInput);expect(()=>saveShelterProfile(d,'직원',false)).toThrow();const saved=saveShelterProfile(d,'직원',true);expect(listShelterProfiles()[0].id).toBe(saved.id);deleteShelterProfile(saved.id);expect(listShelterProfiles()).toEqual([]);localStorage.setItem('hanggo:shelter-profiles','bad');expect(()=>saveShelterProfile(d,'직원',true)).toThrow();expect(localStorage.getItem('hanggo:shelter-profiles')).toBe('bad');});
});
